version: '3.8'
services:
  train:
    build: .
    command: python train.py
    volumes:
      - mnist:/opt/mount

  evaluate:
    build: .
    command: python eval.py
    volumes:
      - mnist:/opt/mount

  infer:
    build: .
    command: python infer.py
    volumes:
      - mnist:/opt/mount
    depends_on:
      - evaluate

volumes:
  mnist:
    driver: local